name: Gradle FRC CI

on:
  pull_request:
    branches:
      - testing
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest  # Matches the RoboRIO's Linux environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Run Simulation Tests
        run: ./gradlew simulateJava  # For testing code in simulation mode

      - name: Upload Test Reports (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/

      - name: Upload Deployment Artifact (Optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deploy-jar
          path: build/libs/*.jar
